// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OtobusProje.Models;

#nullable disable

namespace Otobusum.com.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250905071719_AddOdemeTable")]
    partial class AddOdemeTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OtobusProje.Models.Bakim", b =>
                {
                    b.Property<int>("BakimId")
                        .HasColumnType("int")
                        .HasColumnName("bakim_id");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("aciklama");

                    b.Property<int>("OtobusId")
                        .HasColumnType("int")
                        .HasColumnName("otobus_id");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int")
                        .HasColumnName("personel_id");

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("date")
                        .HasColumnName("tarih");

                    b.HasKey("BakimId")
                        .HasName("PK__Bakim__0F7162E5ED4A309F");

                    b.HasIndex("OtobusId");

                    b.HasIndex("PersonelId");

                    b.ToTable("Bakim");
                });

            modelBuilder.Entity("OtobusProje.Models.Bilet", b =>
                {
                    b.Property<int>("BiletId")
                        .HasColumnType("int")
                        .HasColumnName("bilet_id");

                    b.Property<int>("KoltukNo")
                        .HasColumnType("int")
                        .HasColumnName("koltuk_no");

                    b.Property<DateTime>("SatisTarihi")
                        .HasColumnType("datetime")
                        .HasColumnName("satis_tarihi");

                    b.Property<int>("SeferId")
                        .HasColumnType("int")
                        .HasColumnName("sefer_id");

                    b.Property<int>("YolcuId")
                        .HasColumnType("int")
                        .HasColumnName("yolcu_id");

                    b.HasKey("BiletId")
                        .HasName("PK__Bilet__033C9972EC0362BB");

                    b.HasIndex("SeferId");

                    b.HasIndex("YolcuId");

                    b.ToTable("Bilet");
                });

            modelBuilder.Entity("OtobusProje.Models.Durak", b =>
                {
                    b.Property<int>("DurakId")
                        .HasColumnType("int")
                        .HasColumnName("durak_id");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ad");

                    b.Property<string>("Sehir")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sehir");

                    b.HasKey("DurakId")
                        .HasName("PK__Durak__DFDE714158CECB0B");

                    b.ToTable("Durak");
                });

            modelBuilder.Entity("OtobusProje.Models.Firma", b =>
                {
                    b.Property<int>("FirmaId")
                        .HasColumnType("int")
                        .HasColumnName("firma_id");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ad");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Telefon")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("telefon");

                    b.HasKey("FirmaId")
                        .HasName("PK__Firma__5F84B8AD91DA020A");

                    b.ToTable("Firma");
                });

            modelBuilder.Entity("OtobusProje.Models.FirmaYorum", b =>
                {
                    b.Property<int>("YorumId")
                        .HasColumnType("int")
                        .HasColumnName("yorum_id");

                    b.Property<int>("FirmaId")
                        .HasColumnType("int")
                        .HasColumnName("firma_id");

                    b.HasKey("YorumId")
                        .HasName("PK__FirmaYor__B0FA5C85B2B40CE0");

                    b.HasIndex("FirmaId");

                    b.ToTable("FirmaYorum");
                });

            modelBuilder.Entity("OtobusProje.Models.Odeme", b =>
                {
                    b.Property<int>("OdemeId")
                        .HasColumnType("int")
                        .HasColumnName("odeme_id");

                    b.Property<int>("BiletId")
                        .HasColumnType("int")
                        .HasColumnName("bilet_id");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("datetime")
                        .HasColumnName("odeme_tarihi");

                    b.Property<string>("OdemeTipi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("odeme_tipi");

                    b.Property<decimal>("OdemeTutari")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("odeme_tutari");

                    b.HasKey("OdemeId")
                        .HasName("PK__Odeme__30746959D0F33946");

                    b.HasIndex("BiletId");

                    b.ToTable("Odeme");
                });

            modelBuilder.Entity("OtobusProje.Models.Otobu", b =>
                {
                    b.Property<int>("OtobusId")
                        .HasColumnType("int")
                        .HasColumnName("otobus_id");

                    b.Property<int>("FirmaId")
                        .HasColumnType("int")
                        .HasColumnName("firma_id");

                    b.Property<int?>("Kapasite")
                        .HasColumnType("int")
                        .HasColumnName("kapasite");

                    b.Property<string>("Marka")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("marka");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("plaka");

                    b.HasKey("OtobusId")
                        .HasName("PK__Otobus__4CF290F25157024F");

                    b.HasIndex("FirmaId");

                    b.HasIndex(new[] { "Plaka" }, "UQ__Otobus__0C052B2F76855E86")
                        .IsUnique();

                    b.ToTable("Otobus");
                });

            modelBuilder.Entity("OtobusProje.Models.OtobusYorum", b =>
                {
                    b.Property<int>("YorumId")
                        .HasColumnType("int")
                        .HasColumnName("yorum_id");

                    b.Property<int>("OtobusId")
                        .HasColumnType("int")
                        .HasColumnName("otobus_id");

                    b.HasKey("YorumId")
                        .HasName("PK__OtobusYo__B0FA5C85235E7CF3");

                    b.HasIndex("OtobusId");

                    b.ToTable("OtobusYorum");
                });

            modelBuilder.Entity("OtobusProje.Models.Personel", b =>
                {
                    b.Property<int>("PersonelId")
                        .HasColumnType("int")
                        .HasColumnName("personel_id");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ad");

                    b.Property<string>("Gorev")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gorev");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("soyad");

                    b.Property<string>("Telefon")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("telefon");

                    b.HasKey("PersonelId")
                        .HasName("PK__Personel__48A5539F69FE9315");

                    b.ToTable("Personel");
                });

            modelBuilder.Entity("OtobusProje.Models.Rezervasyon", b =>
                {
                    b.Property<int>("RezervasyonId")
                        .HasColumnType("int")
                        .HasColumnName("rezervasyon_id");

                    b.Property<string>("Durum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("durum");

                    b.Property<int>("KoltukNo")
                        .HasColumnType("int")
                        .HasColumnName("koltuk_no");

                    b.Property<DateTime>("RezervasyonTarihi")
                        .HasColumnType("datetime")
                        .HasColumnName("rezervasyon_tarihi");

                    b.Property<int>("SeferId")
                        .HasColumnType("int")
                        .HasColumnName("sefer_id");

                    b.Property<int>("YolcuId")
                        .HasColumnType("int")
                        .HasColumnName("yolcu_id");

                    b.HasKey("RezervasyonId")
                        .HasName("PK__Rezervas__770E0154E399A685");

                    b.HasIndex("SeferId");

                    b.HasIndex("YolcuId");

                    b.ToTable("Rezervasyon");
                });

            modelBuilder.Entity("OtobusProje.Models.RotaDurak", b =>
                {
                    b.Property<int>("RotaId")
                        .HasColumnType("int")
                        .HasColumnName("rota_id");

                    b.Property<int>("DurakId")
                        .HasColumnType("int")
                        .HasColumnName("durak_id");

                    b.Property<int>("DurakSirasi")
                        .HasColumnType("int")
                        .HasColumnName("durak_sirasi");

                    b.HasKey("RotaId", "DurakId")
                        .HasName("PK__Rota_Dur__07CAA3D8AF38FE19");

                    b.HasIndex("DurakId");

                    b.ToTable("Rota_Durak");
                });

            modelBuilder.Entity("OtobusProje.Models.Rotum", b =>
                {
                    b.Property<int>("RotaId")
                        .HasColumnType("int")
                        .HasColumnName("rota_id");

                    b.Property<string>("Kalkis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("kalkis");

                    b.Property<int?>("MesafeKm")
                        .HasColumnType("int")
                        .HasColumnName("mesafe_km");

                    b.Property<string>("Varis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("varis");

                    b.HasKey("RotaId")
                        .HasName("PK__Rota__0A3744CCBC8FDAFD");

                    b.ToTable("Rota");
                });

            modelBuilder.Entity("OtobusProje.Models.Sefer", b =>
                {
                    b.Property<int>("SeferId")
                        .HasColumnType("int")
                        .HasColumnName("sefer_id");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("fiyat");

                    b.Property<string>("Kalkis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("kalkis");

                    b.Property<int>("OtobusId")
                        .HasColumnType("int")
                        .HasColumnName("otobus_id");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int")
                        .HasColumnName("personel_id");

                    b.Property<int?>("RotaId")
                        .HasColumnType("int")
                        .HasColumnName("rota_id");

                    b.Property<TimeOnly>("Saat")
                        .HasColumnType("time")
                        .HasColumnName("saat");

                    b.Property<int>("SoforId")
                        .HasColumnType("int")
                        .HasColumnName("sofor_id");

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("date")
                        .HasColumnName("tarih");

                    b.Property<string>("Varis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("varis");

                    b.HasKey("SeferId")
                        .HasName("PK__Sefer__AE50B52EFA215C81");

                    b.HasIndex("OtobusId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("RotaId");

                    b.HasIndex("SoforId");

                    b.ToTable("Sefer");
                });

            modelBuilder.Entity("OtobusProje.Models.SeferYorum", b =>
                {
                    b.Property<int>("YorumId")
                        .HasColumnType("int")
                        .HasColumnName("yorum_id");

                    b.Property<int>("SeferId")
                        .HasColumnType("int")
                        .HasColumnName("sefer_id");

                    b.HasKey("YorumId")
                        .HasName("PK__SeferYor__B0FA5C8586A56446");

                    b.HasIndex("SeferId");

                    b.ToTable("SeferYorum");
                });

            modelBuilder.Entity("OtobusProje.Models.Sofor", b =>
                {
                    b.Property<int>("SoforId")
                        .HasColumnType("int")
                        .HasColumnName("sofor_id");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ad");

                    b.Property<string>("EhliyetNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ehliyet_no");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("soyad");

                    b.Property<string>("Telefon")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("telefon");

                    b.HasKey("SoforId")
                        .HasName("PK__Sofor__8B25EFF8222A5BB1");

                    b.HasIndex(new[] { "EhliyetNo" }, "UQ__Sofor__CE5DBA39EBEABFF8")
                        .IsUnique();

                    b.ToTable("Sofor");
                });

            modelBuilder.Entity("OtobusProje.Models.SoforYorum", b =>
                {
                    b.Property<int>("YorumId")
                        .HasColumnType("int")
                        .HasColumnName("yorum_id");

                    b.Property<int>("SoforId")
                        .HasColumnType("int")
                        .HasColumnName("sofor_id");

                    b.HasKey("YorumId")
                        .HasName("PK__SoforYor__B0FA5C85D79B0A5B");

                    b.HasIndex("SoforId");

                    b.ToTable("SoforYorum");
                });

            modelBuilder.Entity("OtobusProje.Models.Yolcu", b =>
                {
                    b.Property<int>("YolcuId")
                        .HasColumnType("int")
                        .HasColumnName("yolcu_id");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ad");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("soyad");

                    b.Property<string>("TcNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("tc_no")
                        .IsFixedLength();

                    b.Property<string>("Telefon")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("telefon");

                    b.HasKey("YolcuId")
                        .HasName("PK__Yolcu__A54471A5F81F16AA");

                    b.HasIndex(new[] { "TcNo" }, "UQ__Yolcu__E61FE7CA6EF1521D")
                        .IsUnique();

                    b.ToTable("Yolcu");
                });

            modelBuilder.Entity("OtobusProje.Models.Yorum", b =>
                {
                    b.Property<int>("YorumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("yorum_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YorumId"));

                    b.Property<int>("Puan")
                        .HasColumnType("int")
                        .HasColumnName("puan");

                    b.Property<DateTime?>("Tarih")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("tarih")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("YolcuId")
                        .HasColumnType("int")
                        .HasColumnName("yolcu_id");

                    b.Property<string>("Yorum1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("yorum");

                    b.HasKey("YorumId")
                        .HasName("PK__Yorum__B0FA5C855DA639AD");

                    b.HasIndex("YolcuId");

                    b.ToTable("Yorum");
                });

            modelBuilder.Entity("OtobusProje.Models.Bakim", b =>
                {
                    b.HasOne("OtobusProje.Models.Otobu", "Otobus")
                        .WithMany("Bakims")
                        .HasForeignKey("OtobusId")
                        .IsRequired()
                        .HasConstraintName("FK__Bakim__otobus_id__619B8048");

                    b.HasOne("OtobusProje.Models.Personel", "Personel")
                        .WithMany("Bakims")
                        .HasForeignKey("PersonelId")
                        .IsRequired()
                        .HasConstraintName("FK__Bakim__personel___628FA481");

                    b.Navigation("Otobus");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("OtobusProje.Models.Bilet", b =>
                {
                    b.HasOne("OtobusProje.Models.Sefer", "Sefer")
                        .WithMany("Bilets")
                        .HasForeignKey("SeferId")
                        .IsRequired()
                        .HasConstraintName("FK__Bilet__sefer_id__693CA210");

                    b.HasOne("OtobusProje.Models.Yolcu", "Yolcu")
                        .WithMany("Bilets")
                        .HasForeignKey("YolcuId")
                        .IsRequired()
                        .HasConstraintName("FK__Bilet__yolcu_id__68487DD7");

                    b.Navigation("Sefer");

                    b.Navigation("Yolcu");
                });

            modelBuilder.Entity("OtobusProje.Models.FirmaYorum", b =>
                {
                    b.HasOne("OtobusProje.Models.Firma", "Firma")
                        .WithMany("FirmaYorums")
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__FirmaYoru__firma__45BE5BA9");

                    b.HasOne("OtobusProje.Models.Yorum", "Yorum")
                        .WithOne("FirmaYorum")
                        .HasForeignKey("OtobusProje.Models.FirmaYorum", "YorumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__FirmaYoru__yorum__44CA3770");

                    b.Navigation("Firma");

                    b.Navigation("Yorum");
                });

            modelBuilder.Entity("OtobusProje.Models.Odeme", b =>
                {
                    b.HasOne("OtobusProje.Models.Bilet", "Bilet")
                        .WithMany("Odemes")
                        .HasForeignKey("BiletId")
                        .IsRequired()
                        .HasConstraintName("FK__Odeme__bilet_id__6C190EBB");

                    b.Navigation("Bilet");
                });

            modelBuilder.Entity("OtobusProje.Models.Otobu", b =>
                {
                    b.HasOne("OtobusProje.Models.Firma", "Firma")
                        .WithMany("Otobus")
                        .HasForeignKey("FirmaId")
                        .IsRequired()
                        .HasConstraintName("FK__Otobus__firma_id__4CA06362");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("OtobusProje.Models.OtobusYorum", b =>
                {
                    b.HasOne("OtobusProje.Models.Otobu", "Otobus")
                        .WithMany("OtobusYorums")
                        .HasForeignKey("OtobusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__OtobusYor__otobu__498EEC8D");

                    b.HasOne("OtobusProje.Models.Yorum", "Yorum")
                        .WithOne("OtobusYorum")
                        .HasForeignKey("OtobusProje.Models.OtobusYorum", "YorumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__OtobusYor__yorum__489AC854");

                    b.Navigation("Otobus");

                    b.Navigation("Yorum");
                });

            modelBuilder.Entity("OtobusProje.Models.Rezervasyon", b =>
                {
                    b.HasOne("OtobusProje.Models.Sefer", "Sefer")
                        .WithMany("Rezervasyons")
                        .HasForeignKey("SeferId")
                        .IsRequired()
                        .HasConstraintName("FK__Rezervasy__sefer__6FE99F9F");

                    b.HasOne("OtobusProje.Models.Yolcu", "Yolcu")
                        .WithMany("Rezervasyons")
                        .HasForeignKey("YolcuId")
                        .IsRequired()
                        .HasConstraintName("FK__Rezervasy__yolcu__6EF57B66");

                    b.Navigation("Sefer");

                    b.Navigation("Yolcu");
                });

            modelBuilder.Entity("OtobusProje.Models.RotaDurak", b =>
                {
                    b.HasOne("OtobusProje.Models.Durak", "Durak")
                        .WithMany("RotaDuraks")
                        .HasForeignKey("DurakId")
                        .IsRequired()
                        .HasConstraintName("FK__Rota_Dura__durak__59063A47");

                    b.HasOne("OtobusProje.Models.Rotum", "Rota")
                        .WithMany("RotaDuraks")
                        .HasForeignKey("RotaId")
                        .IsRequired()
                        .HasConstraintName("FK__Rota_Dura__rota___5812160E");

                    b.Navigation("Durak");

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("OtobusProje.Models.Sefer", b =>
                {
                    b.HasOne("OtobusProje.Models.Otobu", "Otobus")
                        .WithMany("Sefers")
                        .HasForeignKey("OtobusId")
                        .IsRequired()
                        .HasConstraintName("FK__Sefer__otobus_id__5BE2A6F2");

                    b.HasOne("OtobusProje.Models.Personel", "Personel")
                        .WithMany("Sefers")
                        .HasForeignKey("PersonelId")
                        .IsRequired()
                        .HasConstraintName("FK__Sefer__personel___5DCAEF64");

                    b.HasOne("OtobusProje.Models.Rotum", "Rota")
                        .WithMany("Sefers")
                        .HasForeignKey("RotaId")
                        .HasConstraintName("FK__Sefer__rota_id__5EBF139D");

                    b.HasOne("OtobusProje.Models.Sofor", "Sofor")
                        .WithMany("Sefers")
                        .HasForeignKey("SoforId")
                        .IsRequired()
                        .HasConstraintName("FK__Sefer__sofor_id__5CD6CB2B");

                    b.Navigation("Otobus");

                    b.Navigation("Personel");

                    b.Navigation("Rota");

                    b.Navigation("Sofor");
                });

            modelBuilder.Entity("OtobusProje.Models.SeferYorum", b =>
                {
                    b.HasOne("OtobusProje.Models.Sefer", "Sefer")
                        .WithMany("SeferYorums")
                        .HasForeignKey("SeferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SeferYoru__sefer__41EDCAC5");

                    b.HasOne("OtobusProje.Models.Yorum", "Yorum")
                        .WithOne("SeferYorum")
                        .HasForeignKey("OtobusProje.Models.SeferYorum", "YorumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SeferYoru__yorum__40F9A68C");

                    b.Navigation("Sefer");

                    b.Navigation("Yorum");
                });

            modelBuilder.Entity("OtobusProje.Models.SoforYorum", b =>
                {
                    b.HasOne("OtobusProje.Models.Sofor", "Sofor")
                        .WithMany("SoforYorums")
                        .HasForeignKey("SoforId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SoforYoru__sofor__4D5F7D71");

                    b.HasOne("OtobusProje.Models.Yorum", "Yorum")
                        .WithOne("SoforYorum")
                        .HasForeignKey("OtobusProje.Models.SoforYorum", "YorumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SoforYoru__yorum__4C6B5938");

                    b.Navigation("Sofor");

                    b.Navigation("Yorum");
                });

            modelBuilder.Entity("OtobusProje.Models.Yorum", b =>
                {
                    b.HasOne("OtobusProje.Models.Yolcu", "Yolcu")
                        .WithMany("Yorums")
                        .HasForeignKey("YolcuId")
                        .IsRequired()
                        .HasConstraintName("FK__Yorum__yolcu_id__3E1D39E1");

                    b.Navigation("Yolcu");
                });

            modelBuilder.Entity("OtobusProje.Models.Bilet", b =>
                {
                    b.Navigation("Odemes");
                });

            modelBuilder.Entity("OtobusProje.Models.Durak", b =>
                {
                    b.Navigation("RotaDuraks");
                });

            modelBuilder.Entity("OtobusProje.Models.Firma", b =>
                {
                    b.Navigation("FirmaYorums");

                    b.Navigation("Otobus");
                });

            modelBuilder.Entity("OtobusProje.Models.Otobu", b =>
                {
                    b.Navigation("Bakims");

                    b.Navigation("OtobusYorums");

                    b.Navigation("Sefers");
                });

            modelBuilder.Entity("OtobusProje.Models.Personel", b =>
                {
                    b.Navigation("Bakims");

                    b.Navigation("Sefers");
                });

            modelBuilder.Entity("OtobusProje.Models.Rotum", b =>
                {
                    b.Navigation("RotaDuraks");

                    b.Navigation("Sefers");
                });

            modelBuilder.Entity("OtobusProje.Models.Sefer", b =>
                {
                    b.Navigation("Bilets");

                    b.Navigation("Rezervasyons");

                    b.Navigation("SeferYorums");
                });

            modelBuilder.Entity("OtobusProje.Models.Sofor", b =>
                {
                    b.Navigation("Sefers");

                    b.Navigation("SoforYorums");
                });

            modelBuilder.Entity("OtobusProje.Models.Yolcu", b =>
                {
                    b.Navigation("Bilets");

                    b.Navigation("Rezervasyons");

                    b.Navigation("Yorums");
                });

            modelBuilder.Entity("OtobusProje.Models.Yorum", b =>
                {
                    b.Navigation("FirmaYorum");

                    b.Navigation("OtobusYorum");

                    b.Navigation("SeferYorum");

                    b.Navigation("SoforYorum");
                });
#pragma warning restore 612, 618
        }
    }
}
